apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{- if .Values.config }}
{{ toYaml .Values.config | indent 4 }}
{{- end }}
